### ISSUE TITLE
The README is too large

### ISSUE THREAD

**Issue by sergeyklay** [almostearthling/when-command#54]
Usually people like a short introduction. A couple of lines - how to install, what provides, etc. All related documents must be separated to the wiki/readthedocs/gitbook/gitpages/etc.

**Comment by almostearthling** [comment]
I was thinkin about this too: **When** has become quite a complex applet by now, and possibly a better organization for documentation (and maybe a man page) should be created. I'll pursue this goal for the production release.

**Comment by almostearthling** [comment]
@sergeyklay I have finally reorganized the documentation on https://readthedocs.org/ and now it's also more usable.

**Comment by sergeyklay** [comment]
:+1:
