### ISSUE TITLE
Interval condition bug and User Interface

### ISSUE THREAD

**Issue by amoghj8** [almostearthling/when-command#91]
Firstly , in the conditions option , on setting the Interval to say "x" hours , the task takes it to be minutes.Hence, the task is repeated every x "minutes" instead of "hours".
Secondly , when deleting a task or condition is it possible to interchange the Yes and No options as it has been the usual practice.

**Comment by almostearthling** [comment]
Thank you for pointing this out. I'm not sure to understand what you mean by interchanging the _Yes_ and _No_ options: if it's about the position of the buttons in the confirmation message box, I'm afraid that I can't, since standard message boxes are used.

**Comment by amoghj8** [comment]
Alright, I understand.

**Comment by almostearthling** [comment]
The latest release, [v0.9.12-beta.4](https://github.com/almostearthling/when-command/releases/tag/v0.9.12-beta.4), should fix the problem with hours and minutes in the condition creation dialog  box.

**Comment by amoghj8** [comment]
How do I update the package?

**Comment by almostearthling** [comment]
If you installed it through the PPA, it should be sufficient to

```
sudo apt-get update
sudo apt-get upgrade
```

from the command line (alternatively you can wait for Ubuntu to notify that there are available updates); if you're not on Ubuntu and used a package downloaded from the releases page, just grab the new package [here](https://github.com/almostearthling/when-command/releases/tag/v0.9.12-beta.4) and upgrade **When** using `dpkg -i` as explained [here](http://when-documentation.readthedocs.io/en/latest/install.html#package-based-install). If you installed from source, maybe the best option is to delete the installation directory and reinstall as described [here](http://when-documentation.readthedocs.io/en/latest/install.html#install-from-the-source): you will not lose any settings or conditions or tasks anyway.
