### ISSUE TITLE
Support Ubuntu 18.04/18.10 for some events

### ISSUE THREAD

**Issue by logix2** [almostearthling/when-command#93]
Session lock/unlock events are not working in Ubuntu 18.04/18.10. They are shown as "[disabled]" in the event drop-down.

I also have the same "[disabled]" for battery events, but I'm using a desktop without a battery so I'm not sure if that's related to my setup, or something that needs updating in When Command.

**Comment by almostearthling** [comment]
Oops... I didn't notice it on 18.04: probably they changed the DBUS message(s) for the two events. Should be updated: let me just investigate on which message is used in order to add support. Thank you.

**Comment by almostearthling** [comment]
Actually the unlock event might be intercepted, but it seems that lock still doesn't show up when the session is forced to be locked via *Cmd+L*. A reference [here](https://gitlab.gnome.org/GNOME/gnome-shell/issues/741). I'll try to find some sort of a workaround.
