### ISSUE TITLE
Unable to locate package when-command

### ISSUE THREAD

**Issue by kendoori** [almostearthling/when-command#94]
Maybe not doable, but trying to install on Mint 19.1. After doing update, I get this:

Unable to locate package when-command

**Comment by almostearthling** [comment]
Repositories actually work for Ubuntu: did you try to install the [.deb](https://github.com/almostearthling/when-command/releases) directly using

`dpkg -i when-command_0.9.13-beta.1-1_all.deb`

after downloading it?

**Comment by kendoori** [comment]
I was able to install. It wasn't completely obvious where it got installed to, but I did find "when" in the menu.
