### ISSUE TITLE
Time conditions with days of the week not considered

### ISSUE THREAD

**Issue by ethanjosephscott** [almostearthling/when-command#97]
Hey there, anytime when setting up a condition to be triggered at a certain time, I very easily just enter the time, however when I want to run a task for a specific day of the week for example Friday.  The scheduler does not take into consideration anything in the "Week Day" box.  It will just run the task everyday.

I am running this one Ubuntu 18.04, so if I need to test on the supported version I can.

**Comment by almostearthling** [comment]
Hi,

thank you for pointing it out: this shouldn't have anything to do with Ubuntu versions (only DBus based events should be version dependent actually): I just have to take a look at what happens. If I'm not able to reproduce the issue I might ask you to send me a log if you don't mind - this is very unlikely in fact, probably it's just an error in the code.

I'll let you know ASAP.

**Comment by almostearthling** [comment]
I think I solved it. There were two problems, actually. Now the time based check function (namely `TimeBasedCondition._check_condition()`) has changed as follows:

```
    def _check_condition(self):
        self._debug("checking time based condition")
        cur_time = time.time()
        now = time.localtime(cur_time)
        test_tuple = (
            self.year if self.year is not None else now[0],
            self.month if self.month is not None else now[1],
            self.day if self.day is not None else now[2],
            self.hour if self.hour is not None else now[3],
            self.minute if self.minute is not None else now[4],
            0,
            now[6],
            now[7],
            now[8],
        )
        test_time = time.mktime(test_tuple)
        span = max(self.tick_seconds, self.skip_seconds)
        self._debug("checking %.3f - %.3f (=%.3f) in [0-%s]" % (cur_time, test_time, cur_time - test_time, span))
        if self.weekday and now[6] != self.weekday:
            return False
        if 0 < cur_time - test_time <= span:
            return True
        else:
            return False
```

I changed it in two places:

1. the test tuple was built in a wrong way (repeating the use of weekday in the places of both week and year's day);
2. in my opinion the week day and the year day are ignored when the float associated to a certain time is built from a tuple.

For the second reason I introduced a test that checks whether or not the week day is set in the condition, and in such a case just fails if the week day is wrong. It just works as it should in a quick test.

As soon as I can reach my usual development workstation, I'll propagate these changes to the repository and soon after I'll update packages both here and on Launchpad.

Thank you again for pointing this out!

**Comment by almostearthling** [comment]
I released the fix in the repository, new packages will be available in a few minutes.
