### ISSUE TITLE
This Feature is not enabled - Linux Mint 20

### ISSUE THREAD

**Issue by blndr-tommy1441** [almostearthling/when-command#98]
Hi,
I had when-command working fine in Mint 19.2 cinnamon until I upgraded to Mint 20.04.
Now when I add a condition to check for file changes on a directory, I get the error "This feature is not enabled" ... I can't seem to find an answer on how to enable it or fix the issue

**Comment by blndr-tommy1441** [comment]
never mind, all I did was restart when-command and now it works fine

**Comment by almostearthling** [comment]
Hi,

glad to know that it's working again: I'm stuck with Ubuntu 18.04 so I didn't try more recent Gnome releases for myself.

Thank you for reporting anyway!

F.
